# Generated by Django 5.2 on 2025-04-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_description_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
