# Generated by Django 5.2 on 2025-04-08 08:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'svg', 'webp'])])),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=50)),
                ('url', models.URLField(blank=True, unique=True)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('both', 'Both')], default='both', max_length=10)),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The display name of the menu item.', max_length=100)),
                ('url', models.CharField(blank=True, help_text='URL or path for the menu item.', max_length=255, unique=True)),
                ('position', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('both', 'Both')], default='both', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the menu item.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the menu item is active.')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item, if any (for dropdown menus).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
