# Generated by Django 5.2 on 2025-05-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_testimonial_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
