# Generated by Django 5.2 on 2025-04-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_slug'),
        ('core', '0007_product_category'),
    ]

    operations = [
    ]
