# Generated by Django 5.2 on 2025-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='rating',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
