# Generated by Django 5.2 on 2025-05-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_productattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'ordering': ['platform']},
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='location',
        ),
    ]
