# Generated by Django 5.2 on 2025-05-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_socialmedialink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('other', 'Other')], max_length=50),
        ),
    ]
