# Generated by Django 5.2 on 2025-05-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_socialmedialink_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phones', models.TextField(help_text='Separate multiple numbers with commas')),
                ('emails', models.TextField(help_text='Separate multiple emails with commas')),
                ('address', models.TextField()),
            ],
        ),
    ]
