# Generated by Django 5.2 on 2025-05-12 05:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contactdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
