# Generated by Django 5.2 on 2025-05-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_category_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='short_description',
            new_name='description',
        ),
    ]
