# Generated by Django 5.2 on 2025-05-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_short_description_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
