# Generated by Django 5.2 on 2025-05-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_alt_text_product_twitter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
