# Generated by Django 5.2 on 2025-05-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='contact_number',
            new_name='phone_number',
        ),
    ]
